// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBNELtOgp91luiFQR05FxN99zmmZVM8MTo',
    appId: '1:670371597542:web:4dae97097c017b3100ff27',
    messagingSenderId: '670371597542',
    projectId: 'meet-cute-dating-app',
    authDomain: 'meet-cute-dating-app.firebaseapp.com',
    storageBucket: 'meet-cute-dating-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC124xuc9XMQnIiIonQEg8JvheTbI9mqw4',
    appId: '1:670371597542:android:3b607b530abb584a00ff27',
    messagingSenderId: '670371597542',
    projectId: 'meet-cute-dating-app',
    storageBucket: 'meet-cute-dating-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBvmfMXlGt6N73BmJa54G7lFChazXWqQds',
    appId: '1:670371597542:ios:b30d5ce5f8c8c16000ff27',
    messagingSenderId: '670371597542',
    projectId: 'meet-cute-dating-app',
    storageBucket: 'meet-cute-dating-app.firebasestorage.app',
    iosBundleId: 'com.example.franchisoVsCode',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBvmfMXlGt6N73BmJa54G7lFChazXWqQds',
    appId: '1:670371597542:ios:b30d5ce5f8c8c16000ff27',
    messagingSenderId: '670371597542',
    projectId: 'meet-cute-dating-app',
    storageBucket: 'meet-cute-dating-app.firebasestorage.app',
    iosBundleId: 'com.example.franchisoVsCode',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBNELtOgp91luiFQR05FxN99zmmZVM8MTo',
    appId: '1:670371597542:web:92553bd07ff774c900ff27',
    messagingSenderId: '670371597542',
    projectId: 'meet-cute-dating-app',
    authDomain: 'meet-cute-dating-app.firebaseapp.com',
    storageBucket: 'meet-cute-dating-app.firebasestorage.app',
  );
}
